version: '3.8'

services:
    product-service:
        image: product-catalog-service:latest
        ports:
            - "8081:8081"
        networks:
            - app-network

    review-service:
        image: review-service:latest
        ports:
            - "8082:8082"
        networks:
            - app-network
    
    gateway-service:
        image: graphql-gateway-service:latest
        ports:
            - "8080:8080"
        environment:
            PRODUCT_SERVICE_URL: http://product-service:8081
            REVIEW_SERVICE_URL: http://review-service:8082/reviews
        depends_on:
            - product-service
            - review-service
        networks:
            - app-network

networks:
    app-network:
        driver: bridge